# Generated by Django 6.0 on 2026-04-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_favorite_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration_minutes',
            field=models.IntegerField(default=75, help_text='Total session duration in minutes from start time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, help_text='When session was created'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', help_text='Administrative status (manually controlled)', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_in_end',
            field=models.TimeField(help_text='Attendance deadline. Before this = Present, After = Late'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_in_start',
            field=models.TimeField(help_text='When attendance window opens (students marked Present)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_out_start',
            field=models.TimeField(help_text='Late cutoff. After this = attendance not allowed (Timed Out)'),
        ),
    ]
