# Generated by Django 6.0 on 2026-04-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_session_duration_minutes_alter_session_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration_minutes',
            field=models.IntegerField(default=30, help_text='Total session duration in minutes from start time'),
        ),
    ]
