# Generated by Django 6.0 on 2026-04-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_private_key_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='favorite_teacher',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
