# Generated by Django 6.0 on 2026-04-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_favorite_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='private_key',
        ),
    ]
