# Generated by Django 6.0 on 2026-04-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
