from django.urls import path

from .views import (
    api_login,
    api_logout,
    export_attendance_report,
    generate_qr,
    validate_qr,
    check_student_exists,
    list_sessions,
    list_students,
    portal_bootstrap,
    debug_request,
    register_student,
    session_dashboard,
    session_report,
    start_session,
    student_login,
    verify_attendance,
    student_attendance,
    student_attendance_full,
)

urlpatterns = [
    path("login/", api_login, name="api-login"),
    path("logout/", api_logout, name="api-logout"),
    path("register/", register_student, name="register-student"),
    path("student-login/", student_login, name="student-login"),
    path("generate-qr/", generate_qr, name="generate-qr"),
    path("validate-qr/", validate_qr, name="validate-qr"),
    path("check-student/", check_student_exists, name="check-student"),
    path("start-session/", start_session, name="start-session"),
    path("verify-attendance/", verify_attendance, name="verify-attendance"),
    path("sessions/", list_sessions, name="list-sessions"),
    path("students/", list_students, name="list-students"),
    path("dashboard/", session_dashboard, name="session-dashboard"),
    path("portal-bootstrap/", portal_bootstrap, name="portal-bootstrap"),
    path("debug-request/", debug_request, name="debug-request"),
    path("reports/export/", export_attendance_report, name="export-attendance-report"),
    path("session-report/<str:session_code>/", session_report, name="session-report"),
    path("student-attendance/", student_attendance, name="student-attendance"),
    path("student-attendance-full/", student_attendance_full, name="student-attendance-full"),
]